# Generated by Django 3.0.2 on 2020-03-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200316_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='quantity',
            field=models.IntegerField(default=False),
        ),
    ]
