# Generated by Django 3.0.2 on 2020-03-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productsmodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='model_no',
            field=models.CharField(max_length=40),
        ),
    ]
