# Generated by Django 3.0.2 on 2020-03-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200330_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='seller',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
