# Generated by Django 3.0.2 on 2020-03-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200330_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('idno', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsModel',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('idno', models.IntegerField()),
                ('tittle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedCardsModel',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('idno', models.IntegerField()),
                ('card_no', models.IntegerField()),
                ('expiry', models.DateField()),
                ('name_on_card', models.CharField(max_length=40)),
            ],
        ),
    ]
