# Generated by Django 3.0.2 on 2020-03-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_addressmodel_reviewsmodel_savedcardsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardsModel',
            fields=[
                ('gift_id', models.IntegerField(primary_key=True, serialize=False)),
                ('idno', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('gift_card_no', models.IntegerField()),
                ('balance', models.FloatField()),
                ('reciever_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.IntegerField()),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='ordersmodel',
            old_name='cart_id',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='delivered_date',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='ordered_date',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
