# Generated by Django 3.0.2 on 2020-03-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200330_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='locality',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='delivered_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='ordered_date',
            field=models.CharField(max_length=30),
        ),
    ]
