# Generated by Django 3.0.2 on 2020-03-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200331_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='delivered_date',
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='locality',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='ordered_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
