# Generated by Django 3.0.2 on 2020-03-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200331_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcardsmodel',
            name='expiry',
        ),
        migrations.AddField(
            model_name='savedcardsmodel',
            name='expiry_mm',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='savedcardsmodel',
            name='expiry_yy',
            field=models.IntegerField(default=False),
        ),
    ]
