# Generated by Django 3.0.2 on 2020-03-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200331_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='model_no',
            field=models.CharField(max_length=40),
        ),
    ]
