# Generated by Django 3.0.2 on 2020-03-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_ordersmodel_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='address_id',
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='address',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
