# Generated by Django 3.0.2 on 2020-03-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200331_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='city',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='loaclity',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='pin',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='state',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
