# Generated by Django 3.0.2 on 2020-04-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200331_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='photo',
            field=models.ImageField(default=False, upload_to='telivisions/'),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='product_name',
            field=models.CharField(default=False, max_length=500),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='product_price',
            field=models.FloatField(default=False),
        ),
    ]
