# Generated by Django 3.0.2 on 2020-04-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200401_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetailsmodel',
            name='balance',
            field=models.FloatField(default=False),
        ),
    ]
